### ISSUE TITLE
Is there any way to get raw tagging results with simplified characters?

### ISSUE THREAD

**Issue by taeheejeon22** [kaniblu/hanja-tagger#2]
I want to make a Hanja-annotated Korean corpus described in https://github.com/kaniblu/hanja-sisg using hanja-tagger. However, I can't figure out how to use this tagger to make that corpus.

As far as I understand, it seems that there are only two ways to use this tagger.
1) get a raw tagging result with Hanja (only Korean-style Chinese character, "패배(敗北)했다")
2) get a Hanja part of a string with Hanja (Korean-style or Simplified, "败北  ")

What I want to get is "패배(败北)했다". How can I get this by using hanja-tagger?

**Comment by kaniblu** [comment]
Hi, you can achieve this by using `hanjatagger.zh2hans.Zh2Hans` class in the package. `HanjaTagger` uses the aforementioned class to convert traditional Chinese to the simplified. 

Here is an example:
```python
>>> from hanjatagger import Hanjaro
>>> from hanjatagger.zh2hans import Zh2Hans
>>> z2h = Zh2Hans()
>>> hjr = Hanjaro()
>>> hjr.open()
>>> z2h.convert(hjr.query("패배했다"))
"패배(败北)했다"
```

Hope this helps.

**Comment by taeheejeon22** [comment]
It works. I think it should be added in README.md.

Anyway, thanks for your help!

**Comment by kaniblu** [comment]
Thanks for the suggestion. Have a good day.
